Exercícios do Bloco 4.3
wandersonsales-dev/trybe-exercises pull request #8
Opened 2021-02-27 03:57 UTC by wandersonsales-dev

2021-02-27 04:23 UTC, LucasPedroso requested changes
Muito bom a idéia do Exercício 4

2021-02-27 04:23 UTC, LucasPedroso commented on bloco_4/dia_3/ex02.js
> +  lineTriangle += ' *';
Acredito que deveria tirar esse espaço para ficar igual ao pedido no exercício, o que acha?
```suggestion
  lineTriangle += '*';
```

2021-02-27 04:59 UTC, wandersonsales-dev commented on bloco_4/dia_3/ex02.js
> +  lineTriangle += ' *';
Show Lucas! Tinha colocado esse espaço só pra ficar mais nítido as alterações no console. Acabei esquecendo de retirar kkk. Muito obrigado! :rocket:

2021-02-27 20:34 UTC, wandersonsales-dev commented
> Muito bom a idéia do Exercício 4

Cara, se não fôsse o Debug... kkkkkk O importante é que deu certo!
Obrigado pelo feedback, @LucasPedroso :rocket:

2021-02-27 22:01 UTC, merged

2021-02-28 22:08 UTC, alexandremolive commented
Muito bom Wanderson! Depois vou olhar com mais calma sua resolução do exercício 5, ainda tô enroscado neste aí.

2021-02-28 22:18 UTC, wandersonsales-dev commented
> Muito bom Wanderson! Depois vou olhar com mais calma sua resolução do exercício 5, ainda tô enroscado neste aí. 

Vlw @alexandremolive! Deu um trabalho mas deu certo kkkk. Usa o debug que vai facilitar bastante 🚀